services:
  chat:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVEPATH: ":8904"
      secrets:
        - admin_password
        - channels
    ports:
      - "8904:6060"

secrets:
  admin_password:
    environment: ADMIN
  channels:
    environment: CHANNELS
